title: "NaNa Mathis"
email: nanarhmathis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio overview of all the projects NaNa Mathis worked on during the MLH Explorer Fellowship.
baseurl: "/" 
url: "/mlh-portfolio" 
twitter_username: nana_this
github_username:  n-mathis
sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
theme: jekyll-theme-minimal
